In [2]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
# Handling Categorical Variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# Importing the dataset
dataset = pd.read_csv('sample_data.csv')

In [18]:
dataset.head()

   Colour Size  Price   Qty
0   green    M   10.5  1000
1  yellow    S   14.5  3444
2     red    S   15.0  1246

In [20]:
# Encoding the size column  (Ordinal Encoding)

dataset['Size'] = dataset['Size'].map({'S': 1, 'M': 2, 'L': 3})

In [21]:
dataset.head()

   Colour  Size  Price   Qty
0   green     2   10.5  1000
1  yellow     1   14.5  3444
2     red     1   15.0  1246

In [22]:
# Encoding the colour column (One Hot Encoding) for nominal data variables
# using get_dummies() method of pandas

#dataset2 = pd.get_dummies(dataset, columns=['Colour'])  both are same
dataset2 = pd.get_dummies(dataset[['Colour', 'Size', 'Price','Qty']])
dataset2.head()

   Size  Price   Qty  Colour_green  Colour_red  Colour_yellow
0     2   10.5  1000          True       False          False
1     1   14.5  3444         False       False           True
2     1   15.0  1246         False        True          False

In [28]:
# the last column has multicollinearity problem as it is highly correlated with the 2 colour columns, so we can drop it to avoid the dummy variable trap

dataset2 = pd.get_dummies(dataset[['Colour', 'Size', 'Price','Qty']], drop_first=True)
dataset2.head()

   Size  Price   Qty  Colour_red  Colour_yellow
0     2   10.5  1000       False          False
1     1   14.5  3444       False           True
2     1   15.0  1246        True          False

In [ ]:
# other encoding techniques for categorical variables are Label Encoding, Binary Encoding, Target Guided Encoding, etc.

In [25]:
dataset2.columns

Index(['Size', 'Price', 'Qty', 'Colour_red', 'Colour_yellow'], dtype='object')

In [36]:
# Scaling the features
# Standardization (Z-score Normalization) is a common technique for feature scaling. It transforms the data to have a mean of 0 and a standard deviation of 1.

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
dataset2_scaled = dataset2.copy()
dataset2_scaled[['Size','Price','Qty']] = sc.fit_transform(dataset2[['Size','Price','Qty']])
dataset2_scaled

       Size     Price       Qty  Colour_red  Colour_yellow
0  1.414214 -1.406930 -0.816094       False          False
1 -0.707107  0.579324  1.408293       False           True
2 -0.707107  0.827606 -0.592199        True          False

In [37]:
# standard deviation is 1 and mean is 0 after standardization
print('Mean:', dataset2_scaled.mean())
print('Standard Deviation:', dataset2_scaled.std())

Mean: Size             1.480297e-16
Price           -2.960595e-16
Qty             -1.110223e-16
Colour_red       3.333333e-01
Colour_yellow    3.333333e-01
dtype: float64
Standard Deviation: Size             1.224745
Price            1.224745
Qty              1.224745
Colour_red       0.577350
Colour_yellow    0.577350
dtype: float64

In [16]:
# standard deviation of 2,6,10)

a = [2, 6, 10]
print('Mean:', np.mean(a))
print('Standard Deviation:', np.std(a))

Mean: 6.0
Standard Deviation: 3.265986323710904

In [31]:
# after scaling the original data is lost, so we can convert the scaled data back to a dataframe and assign the column names to it

dataset2_scaled_df = pd.DataFrame(dataset2_scaled, columns=dataset2.columns)
dataset2_scaled_df.head()

       Size     Price       Qty  Colour_red  Colour_yellow
0  1.414214 -1.406930 -0.816094   -0.707107      -0.707107
1 -0.707107  0.579324  1.408293   -0.707107       1.414214
2 -0.707107  0.827606 -0.592199    1.414214      -0.707107

In [32]:
# after fitting the model, we can use the inverse_transform() method to get back the original data from the scaled data

dataset2_original = sc.inverse_transform(dataset2_scaled)
dataset2_original_df = pd.DataFrame(dataset2_original, columns=dataset2.columns)

In [33]:
dataset2_original_df.head()

   Size  Price     Qty  Colour_red  Colour_yellow
0   2.0   10.5  1000.0         0.0            0.0
1   1.0   14.5  3444.0         0.0            1.0
2   1.0   15.0  1246.0         1.0            0.0